---
# file: roles/ssh/tasks/main.yml
- name: Setup
  include: setup.yml
  
- name: Set port
  include: port.yml
  
- name: Add user
  include: user.yml
  when: ssh_user != '' and ssh_public_key != '' and ssh_private_key != ''




